### ISSUE TITLE
關於Monero挖礦的一些問題，實在找不到您的聯繫方式所以冒昧地在不相關的repository下提了issues

### ISSUE THREAD

**Issue by 5z1punch** [Lafudoci/Trinity2GO#1]
您好，我拜讀了您寫的[Monero (XMR) 介紹及使用教學](https://lafudoci.gitbooks.io/monero-xmr/content/)，並且按照您給出的cpu挖礦方法以及推薦的礦池 monerohash.com:3333 進行了挖礦測試。因為不想下載完整的區塊鏈，所以我使用了線上錢包 [mymonero](https://mymonero.com/#/) ，因為僅僅是測試，所以我使用了1個cpu和礦池 monerohash.com:3333 測試了挖礦，但是過了3天時間，我的mymonero 帳戶中的Balance仍然為0，我確定沒有寫錯錢包地址，而且礦池也持續接受了我的請求。我查閱了相關資料，發現接近50塊GTX 750顯卡一天才能挖到一個xmr，但是礦池每發現一個block不就會結算一次嗎（其實我不太清楚是否一個block是否就是一個xmr），我的挖礦程式已經在vps上運行了3天了，仍沒有xmr入帳，請問這會是何種原因導致的呢。期待您的解答。如果可以的話，可否告知我您的電子郵件，方便以後向您請教關於xmr的問題。謝謝。我的郵箱是 th3s3v3n.shell@gmail.com

**Comment by Lafudoci** [comment]
您好
從您的狀況來看，應該是累積的金額還沒有達到礦池的的出帳門檻喔
目前monero出帳門檻為1xmr，若以常見1CPU的算力來看會需要不短的天數才能累計到
您可以到monerohash首頁下方輸入挖礦用的地址以查詢Pending Balance來估算多久能夠達到出帳門檻
以上希望有幫助

另外
我已經把gitbook的討論區功能開啟
https://www.gitbook.com/book/lafudoci/monero-xmr/discussions
歡迎提出問題來討論

**Comment by 5z1punch** [comment]
Thank you very very much.
